### ISSUE TITLE
shadows don't render

### ISSUE THREAD

**Issue by DARKLOL680** [jbritain/Ebin-Shaders-Resurrected#2] opened 2024-05-08 12:19 UTC
**Describe the bug**
shadows don't render at all even with PCSS turned off

**Screenshots**
![PCSS off](https://github.com/jbritain/Ebin-Shaders-Resurrected/assets/121734819/c3a1ffc6-847c-4a88-af39-8ba05fd7f73f)

**Minecraft Version/Mods (please complete the following information):**
 - Minecraft Version 1.20.1
 - Shaders mod Iris 1.6.17

**Specifications (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA RTX 4070

[latest.log](https://github.com/jbritain/Ebin-Shaders-Resurrected/files/15248728/latest.log)

**Comment by jbritain** [comment] 2024-05-08 13:23
I've noticed you have a lot of mods installed, does it occur without the mods?

**Comment by jbritain** [comment] 2024-05-08 13:34
Okay, I don't think it's a mod related issue. It looks like there's something going on with how Iris compatibility patches undeclared variables (which I really need to sort anyway, the amount of warnings it generates is something).

I can't replicate the errors on my machine but I will try to mitigate the cause of all the warnings and hopefully that'll sort it.

**Comment by jbritain** [comment] 2024-05-15 15:14
So I've had a few other people on NVIDIA GPUs try the shader and it works fine for all of them, which leads me to believe that this is in fact a mod related issue.

I don't really have much choice but to close the issue because I've no idea what's causing it.

**Closed as completed by jbritain** 2024-05-15 15:14 UTC
Labels: bug, wontfix
